### ISSUE TITLE
Training Jasper on Arabic 

### ISSUE THREAD

**Issue by kkiyani** [TensorSpeech/TensorFlowASR#116]
Hello,
can anybody please list down the changes I need to make in the library in order to train the model successfully. 
For instance, I have already made changes to the file (english.characters) by adding Arabic characters.
What else do I need to change?

**Comment by usimarit** [comment]
@kkiyani you need to change the paths in the `config.yml` file, creates the `transcripts.tsv` files for your dataset by following the installation and setup training and testing instruction. Then use the scripts in the `examples/jasper` to train or test the model.
Note: This is the unofficial implementation and hasn't been tested properly due to the lack of resources (and no NovoGrad). So I have no guarantee that it would perform the same as the original one in the [NVIDIA/OpenSeq2Seq](https://github.com/NVIDIA/OpenSeq2Seq) but the structure is very similar.

**Comment by kkiyani** [comment]
[
![error_tfasr](https://user-images.githubusercontent.com/67789395/105669927-04cc4000-5f02-11eb-8b23-dd24d38ecfd8.PNG)
](url)


facing error while training jasper, even after making the suggested changes

**Comment by usimarit** [comment]
@kkiyani Your dataset contains unknown characters (see in the KeyError), please normalize the dataset's transcripts so that they contain only "lowercase" Arabic characters and some additional characters that you want to add (for example: ' or ")

**Comment by usimarit** [comment]
I'll close the issue here, if it still shows errors, feel free to reopen.
