### ISSUE TITLE
Create new results file for each test

### ISSUE THREAD

**Issue by mjurkus** [TensorSpeech/TensorFlowASR#126]
Me and other users https://github.com/TensorSpeech/TensorFlowASR/issues/124#issuecomment-767545714 ran into the issue, that tests file is reused and it's not immediately obvious.

I would suggest to have just a separate folder for `test.tsv` files and make it so each test has a separate file.

**Comment by usimarit** [comment]
@mjurkus You can use the argument to change file name:[https://github.com/TensorSpeech/TensorFlowASR/blob/3a4d4eef8815e71ebc2df618ba9a4634e410ccc0/examples/conformer/test_subword_conformer.py#L51](https://github.com/TensorSpeech/TensorFlowASR/blob/3a4d4eef8815e71ebc2df618ba9a4634e410ccc0/examples/conformer/test_subword_conformer.py#L51)
You have to put a different file name when you want to test on another dataset, otherwise it will behave like resuming the test by counting the tested records, skip them and continue testing on untested records.

**Comment by mjurkus** [comment]
`parser.add_argument("--output_name", type=str, default="test", help="Result filename name prefix")`

Ok. I didn't go into implementation for it but maybe it should be documented, that it will do that?
> resuming the test by counting the tested records, skip them and continue testing on untested records

I too stepped on the same landmine in my experimentations.

**Comment by usimarit** [comment]
The testing scripts are updated and we have an option to overwrite or create a new test results. So I'll close this issue here 😄
