### ISSUE TITLE
Testing fails for conformer model

### ISSUE THREAD

**Issue by flaviofafe1414** [TensorSpeech/TensorFlowASR#191]
I'm trying to run con.test.py, but I'm getting the following error:

TFRecords already existed: test
2021-04-27 22: 25: 58.737252: I tensorflow / stream_executor / platform / default / dso_loader.cc: 48] Dynamic library successfully opened libcublas.so.10
2021-04-27 22: 25: 58.905627: I tensorflow / stream_executor / platform / default / dso_loader.cc: 48] Dynamic library successfully opened libcudnn.so.7
871/871 [==================================] - 265s 304ms / step
Saving result in /home/flavio/TensorFlowASR/examples/conformer/models/local/conformer/checkpoints/test.tsv ...
0batch [00:00,? Batch / s] Traceback (most recent last call):
    Test.py file, line 114, in <module>
      path, duration, _ = test_dataset.entries [i]
AttributeError: the object 'ASRTFRecordDataset' has no attribute 'entries'

**Comment by usimarit** [comment]
@flaviofafe1414 the example `test.py` is not written to be used with ASRTFRecordDataset because the results will be written to the tsv file as `PATH\tDURATION\tGROUNDTRUTH\tGREEDY\tBEAMSEARCH\n` and the `PATH`, `DURATION` only available in the `entries` property, which may not be available in ASRTFRecordDataset, if you want to use ASRTFRecordDataset, then you will have to customize the file in your own way (like ignoring the PATH and DURATION by setting them to empty string '')

**Comment by flaviofafe1414** [comment]
It works for me, perfectly!
