### ISSUE TITLE
Are the metrics in Contextnet given in percentages?

### ISSUE THREAD

**Issue by vaibhav016** [TensorSpeech/TensorFlowASR#194]
@usimarit  Hello,
While testing, i recieved the following metrics. 
 
      greedy_wer: 0.7827335596084595
      greedy_cer: 0.4933541715145111
      beamsearch_wer: 0.3287621736526489
      beamsearch_cer: 0.16175541281700134

The paper on contextnet, refers to word error rate in percentages, like their best score is 1.9%. Based on my current metrics, lets say 0.32 beam search word error rate. So is it actually 32%, or does it mean 0.32 % ?  

Please correct me if I am wrong.

**Comment by usimarit** [comment]
@vaibhav016 the metrics on paper is %, but the actual WER, CER are not %, they multiply the result with 100 so that the results have a unit to compare, so I remove the part "multiply 100" so that the results are truly WER, CER.
In conclusion, the results in TensorFlowASR v1.x have no unit, and you can multiply them to turn them to % (which means in this case, your beam search wer is 32.87%)

**Comment by vaibhav016** [comment]
@usimarit Okay. Thank you so much for clearing this issue.
