### ISSUE TITLE
test.py not run with cpu=false

### ISSUE THREAD

**Issue by hoangnhevf** [TensorSpeech/TensorFlowASR#283]
Hi, when I run TensorFlowASR\examples\contextnet\test.py with cpu=false, system run very slow and not response results.
When i readme.md (it only not support tpu, => i set cpu = false, have system run gpu?), program stopped here:
![image](https://github.com/TensorSpeech/TensorFlowASR/assets/80943002/100c64c0-0503-4213-b180-c98d1d8103f5)

Please support me,
Thanks

Python: 3.8
Tensorflow-gpu: 2.8
I tried with Cuda toolkit: 11.0, 11.1, 11.2
GPU: GTX 2070

**Comment by Aegon007** [comment]
您好，您的邮件我已收到。我会尽快给您回复。祝好！

**Comment by ROZBEH** [comment]
Hi there,
Thanks for putting together this repo. Great resource.
Any progress on this?
Thanks.

**Comment by nglehuy** [comment]
this will be fixed in the v2

**Comment by nglehuy** [comment]
TensorFlowASR v1.x is not deprecated and no longer supported

TensorFlowASR v2.x drops the use of tensorflow-io package, and the naive implementation of rnnt beam search

The implementation of greedy decoding is fixed by limiting number of tokens per frame, which avoids loop indefinitely

Please try with the v2.x version, the pretrained contextnet can be found [here](https://github.com/TensorSpeech/TensorFlowASR/tree/7d18d2327d65caf8b234b903d42ee22d72039078/examples/models/transducer/contextnet/results/wordpiece)

Close here, feel free to reopen if you have further questions
