### ISSUE TITLE
about vocabulary

### ISSUE THREAD

**Issue by alsm168** [TensorSpeech/TensorFlowASR#29]
hello, when train transducer, whether the vocabulary should include **S** and **/S** as the sentence start and sentence end tag?thanks.

**Comment by usimarit** [comment]
There's no need include **S** and **/S** _if in your dataset doesn't have those characters_.
For example, in librispeech, there are only characters from english alphabet (a-z), space and the '. So vocabulary (if you use characters model instead of subwords model) is (a-z) + space + ' + blank = 29 characters as in the [english.txt](https://github.com/usimarit/TiramisuASR/tree/master/vocabularies/english.txt). But if librispeech contained two more characters **S** and **/S**, you would have to include those two characters in the vocabulary file.
In sum, vocabulary depends on transcripts in you dataset.

**Comment by alsm168** [comment]
I got it, Thank you for your explanation.
